### ISSUE TITLE
project --create

### ISSUE THREAD

**Issue by allyssonallan** [chanzuckerberg/czid-cli#47]
Hi guys, could you create a project --create to make whole process terminal-friendly?

Maybe a parsing flag with --private or --open with link directly to basespace --basespace or other strategy.

**Comment by jonalim** [comment]
This feature hasn't been added yet. Being able to programmatically create projects would go a long way toward persuading my sequencing core to use CZID. @allyssonallan Would you consider re-opening the issue?
